### ISSUE TITLE
Adding EOS folder to eic-shell

### ISSUE THREAD

**Issue by michael-pitt** [eic/containers#1]
**Is your feature request related to a problem? Please describe.**
When setting up `eic-shell` on lxplus.cern.ch, the mounted folder `/eos` is removed.

**Describe the solution you'd like**
Add `/eos` to `install.sh` (L186)

**Comment by wdconinc** [comment]
I guess I should pay attention to these issues... Only just now noticed this here. Sorry!

We can't create all possible directories in the container that various systems use for their filesystem mount point. We have set ourselves as the limitation to only support the file systems that the DOE host labs use (BNL and JLab). See https://github.com/eic/eic-shell/blob/647763d082795f765e92bc99d5c44b15d3b84ba9/install.sh#L186.

Other filesystems can be mounted by using the `SINGULARITY_OPTIONS` variable, e.g.
```
export SINGULARITY_OPTIONS="-B/eos:/mnt"
```
to mount `/eos` at `/mnt` in the container.
