### ISSUE TITLE
Add xterm to the image

### ISSUE THREAD

**Issue by buddhasystem** [eic/containers#13]
It is often convenient to have the possibility to open a xterm window into a running container, and/or debug X11 issues that may occur when ROOT fails to start in the GUI mode, for a variety of reasons. Installing xterm on the fly is possible but not too convenient, and because of its general utility perhaps it's better to have it in the base image.

**Comment by wdconinc** [comment]
See https://eicweb.phy.anl.gov/containers/eic_container/-/merge_requests/880. Feel free to close when you notice that MR has merged (or when you notice that xterm is installed). It should be there by tomorrow.

**Comment by wdconinc** [comment]
https://eicweb.phy.anl.gov/containers/eic_container/-/merge_requests/880 has been merged; xterm now installed in eic-shell. Please reopen if xterm is not functional when it rolls out to cvmfs or docker hub.

**Comment by wdconinc** [comment]
https://eicweb.phy.anl.gov/containers/eic_container/-/merge_requests/885:

> Because xterm depends on termcap, and termcap fails to build on modern clang, you get xeyes instead.

**Comment by kkauder** [comment]
> https://eicweb.phy.anl.gov/containers/eic_container/-/merge_requests/885:
> 
> > Because xterm depends on termcap, and termcap fails to build on modern clang, you get xeyes instead.

What am I missing? Is xterm installed? Why would I want xeyes (I do use it from time to time but can just apt install it)?

**Comment by wdconinc** [comment]
@buddhasystem wanted xterm to debug X connections, and couldn't apt install it because of network setup issues, so it was added to the container. It causes issues, so I had to remove it again. Xeyes serves the same purpose of debugging X connections.
