### ISSUE TITLE
Request package py-wurlitzer

### ISSUE THREAD

**Issue by Chao1009** [eic/containers#3]
This package provides a nice feature to "Capture C-level stdout/stderr pipes in Python via os.dup2."
https://spack.readthedocs.io/en/latest/package_list.html#py-wurlitzer

This is very useful when someone uses the DDG4 kernel in Python.

**Comment by wdconinc** [comment]
Move to https://eicweb.phy.anl.gov/containers/eic_container/-/merge_requests/723
